"""Canonical, source-grounded assessment content for the EM MCP server."""

from typing import Final

HABITS: Final[dict[str, dict[str, object]]] = {
    "Inquisitiveness": {"category": "Curiosity", "official_description": "Applies curiosity about a continuously changing world.", "core_theme": "Ask discerning questions, decompose claims, and pursue root causes before accepting an answer.", "look_for": ["prioritized question sequence", "verified root-cause or first-principles chain", "explicit assumptions", "revision after checking evidence"], "do_not_count": "Generic questions, an AI explanation, or a summary the student does not investigate.", "related_behaviors": ["Asks discerning, open-ended questions before offering solutions", "Gathers data to support and refute ideas"]},
    "Contrarian Thinking": {"category": "Curiosity", "official_description": "Explores alternative or disruptive views of accepted solutions.", "core_theme": "Challenge accepted solutions and functional fixedness by developing and testing credible alternatives.", "look_for": ["functional reframing", "credible alternative map", "serious critique of the preferred option", "explicit comparison with a disruptive view"], "do_not_count": "Reflexive disagreement, an unevaluated brainstorm, or an AI-generated alternative that is never tested.", "related_behaviors": ["Asks discerning, open-ended questions before offering solutions", "Gathers data to support and refute ideas"]},
    "Opportunity Seeking": {"category": "Curiosity", "official_description": "Identifies trends and unmet needs to uncover new opportunities.", "core_theme": "Find unmet jobs, gaps, or trends that indicate a problem worth solving.", "look_for": ["documented unmet need", "white-space gap", "stakeholder or trend evidence", "rationale for why the opportunity matters"], "do_not_count": "A generic idea list or a problem chosen only because it is convenient or assigned.", "related_behaviors": ["Finds opportunities to create value"]},
    "Experimentation": {"category": "Curiosity", "official_description": "Constantly experiments and iterates to test ideas and explore what-ifs.", "core_theme": "Frame hypotheses and learn through controlled comparison, iteration, and evidence.", "look_for": ["testable hypothesis", "variables and controls", "comparison design", "results across iterations", "conclusion tied to what changed"], "do_not_count": "Many variants, trial and error without a comparison design, or a single successful run.", "related_behaviors": ["Gathers data to support and refute ideas", "Embraces and learns from failure"]},
    "Confronting Ambiguity": {"category": "Curiosity", "official_description": "Operates with care in complex and uncertain environments.", "core_theme": "Remain productive without false certainty by surfacing assumptions, classifying uncertainty, and bounding unknowns.", "look_for": ["assumption map", "ranges or conditional claims", "known/unknown/unknowable distinctions", "uncertainty-driven next step"], "do_not_count": "A confident answer to an underspecified problem or a risk list that does not characterize uncertainty.", "related_behaviors": ["Adapts to changing conditions", "Asks discerning, open-ended questions before offering solutions"]},
    "Future-Minded": {"category": "Curiosity", "official_description": "Considers emerging trends in people, systems, and environments.", "core_theme": "Consider genuinely divergent futures, their dependencies, and signals indicating which future is emerging.", "look_for": ["multiple plausible scenarios", "backcast dependencies", "leading indicators", "decision stress-tested across futures"], "do_not_count": "A single forecast, trend summary, or unsupported prediction.", "related_behaviors": ["Finds opportunities to create value", "Identifies impact for various stakeholders", "Adapts to changing conditions"]},
    "Creativity": {"category": "Connections", "official_description": "Integrates information from disparate sources to spark new ideas.", "core_theme": "Recombine distant ideas, analogies, and design elements into a novel and useful concept.", "look_for": ["morphological combination", "TRIZ or SCAMPER transformation", "cross-domain analogy", "explanation of how the transfer works"], "do_not_count": "Novelty alone, a long idea list, or the first conventional AI suggestion.", "related_behaviors": ["Integrates information from many sources", "Finds opportunities to create value"]},
    "Systems Thinking": {"category": "Connections", "official_description": "Recognizes interdependencies in systems and identifies leverage points.", "core_theme": "See system boundaries, interdependencies, feedback loops, accumulations, and leverage points beneath events.", "look_for": ["causal-loop, stock-and-flow, or Iceberg analysis", "reinforcing and balancing loops", "defended leverage point", "interactions across subsystems"], "do_not_count": "A component list, linear cause-and-effect chain, or isolated efficiency improvement.", "related_behaviors": ["Integrates information from many sources", "Identifies impact for various stakeholders"]},
    "Knowledge Synthesis": {"category": "Connections", "official_description": "Combines ideas, information, and experiences to form new understanding.", "core_theme": "Connect and reconcile sources and experience into understanding the student can explain and use.", "look_for": ["linked concepts", "explicit relationships among sources", "conflicts identified and reconciled", "synthesis applied to a decision"], "do_not_count": "Separate summaries, a literature list, or an AI-produced map the student cannot defend.", "related_behaviors": ["Integrates information from many sources", "Gathers data to support and refute ideas"]},
    "Implications Thinking": {"category": "Connections", "official_description": "Anticipates the long-term impacts and consequences of actions.", "core_theme": "Trace decisions beyond immediate effects to second- and third-order consequences and unintended outcomes.", "look_for": ["Futures Wheel or consequence chain", "downstream effects across time or subsystems", "affected parties", "mitigation of a non-obvious consequence"], "do_not_count": "Immediate pros and cons or a generic risk list that stops at first-order effects.", "related_behaviors": ["Identifies impact for various stakeholders"]},
    "Strategic Thinking": {"category": "Connections", "official_description": "Develops long-term strategies with clear milestones.", "core_theme": "Choose and defend a sequence of milestones and dependencies that reaches a long-term goal under constraint.", "look_for": ["milestone path", "critical dependencies and slack", "sequencing rationale", "tradeoffs about now/later/not at all", "adaptation triggers"], "do_not_count": "A polished calendar, Gantt chart, or task list with no strategic rationale.", "related_behaviors": ["Adapts to changing conditions", "Integrates information from many sources"]},
    "Risk Awareness": {"category": "Connections", "official_description": "Proactively incorporates risk management into decision-making.", "core_theme": "Surface, prioritize, mitigate, monitor, and own the failure modes that matter.", "look_for": ["pre-mortem, FMEA, or fault tree", "justified prioritization", "mitigation", "monitoring trigger and owner", "decision changed by risk"], "do_not_count": "A boilerplate risk list, unverified AI FMEA, or table with no ownership or response.", "related_behaviors": ["Gathers data to support and refute ideas", "Identifies impact for various stakeholders", "Adapts to changing conditions"]},
    "Value Awareness": {"category": "Creating Value", "official_description": "Focuses on solutions where extraordinary value can be created.", "core_theme": "Locate opportunities where a solution can create disproportionate, evidence-backed benefit for others.", "look_for": ["Pareto or value-stream analysis", "recipient named", "pains relieved and gains created", "benefit magnitude", "validated priority"], "do_not_count": "More output, effort saved, or internal efficiency presented as value without a recipient or outcome.", "related_behaviors": ["Finds opportunities to create value", "Communicates value propositions appropriately to different stakeholders"]},
    "Customer-Centric Thinking": {"category": "Creating Value", "official_description": "Frames efforts in terms of stakeholders' actual needs.", "core_theme": "Ground work in real stakeholders' jobs, experiences, pains, and gains rather than assumed needs.", "look_for": ["real stakeholder evidence", "jobs-to-be-done or empathy finding", "unexpected need", "requirement or decision changed by evidence"], "do_not_count": "A synthetic persona, AI roleplay used as the customer, or feature preferences without probing the underlying job.", "related_behaviors": ["Asks discerning, open-ended questions before offering solutions", "Identifies impact for various stakeholders", "Communicates value propositions appropriately to different stakeholders"]},
    "Impact Thinking": {"category": "Creating Value", "official_description": "Seeks outcomes that produce meaningful and scalable benefits for others.", "core_theme": "Validate a causal pathway at small scale, then pursue outcomes that can scale without breaking.", "look_for": ["theory of change", "validated outcome evidence", "scale assumptions", "unit economics or capacity constraints", "decision about what must persist at scale"], "do_not_count": "Reach, adoption, or output volume treated as impact without a validated causal link.", "related_behaviors": ["Identifies impact for various stakeholders", "Finds opportunities to create value", "Communicates value propositions appropriately to different stakeholders"]},
    "Socially Minded": {"category": "Creating Value", "official_description": "Prioritizes creating meaningful and positive societal impacts.", "core_theme": "Account for societal, ethical, environmental, and distributional effects, especially for affected people with little power.", "look_for": ["broad stakeholder map", "low-power/high-stakes groups", "life-cycle effects", "positive and negative outcomes", "ethical tradeoff changing the design"], "do_not_count": "A token ethics paragraph, only the paying customer's view, or optimization of the easiest metric.", "related_behaviors": ["Identifies impact for various stakeholders"]},
    "Persistence": {"category": "Creating Value", "official_description": "Maintains agency and resilience to achieve goals through obstacles and failures.", "core_theme": "Sustain productive struggle, adapt after obstacles, and convert failure into transferable learning.", "look_for": ["obstacle log", "strategy changes", "feedback sought and used", "after-action review", "lesson applied to a later attempt"], "do_not_count": "Time spent, repeated effort without adaptation, or using AI to bypass the difficult step.", "related_behaviors": ["Embraces and learns from failure", "Adapts to changing conditions"]},
    "Resourcefulness": {"category": "Creating Value", "official_description": "Solves problems creatively with available resources.", "core_theme": "Solve creatively within a real resource envelope by repurposing and recombining what is available.", "look_for": ["explicit inventory and constraint", "cross-domain reuse", "feasible recombination", "calculation or test within the fixed envelope"], "do_not_count": "Automation alone, a shopping list, or an AI proposal assuming unavailable resources.", "related_behaviors": ["Adapts to changing conditions", "Finds opportunities to create value"]},
}

BEHAVIORS: Final[dict[str, dict[str, object]]] = {
    "Adapts to changing conditions": {"definition": "Recognizes change, reassesses the plan, and pivots while protecting core objectives.", "anchors": ["Ignores change or continues a clearly unviable plan.", "Acknowledges change but adjusts narrowly or needs guidance.", "Promptly reprioritizes and modifies the approach using new information.", "Anticipates change, prepares contingencies, and adapts without sacrificing quality."]},
    "Asks discerning, open-ended questions before offering solutions": {"definition": "Uses thoughtful inquiry to uncover context, assumptions, root causes, and hidden complexity before proposing a fix.", "anchors": ["Jumps to a solution or asks only closed, confirming questions.", "Asks some clarifying questions but probes narrowly or stops early.", "Uses open questions and follow-ups across relevant perspectives before deciding.", "Adapts a probing sequence and guides the team toward data-informed understanding."]},
    "Communicates value propositions appropriately to different stakeholders": {"definition": "Connects a solution's worth to each audience's actual needs, goals, and concerns.", "anchors": ["Uses the same technical explanation for all audiences and omits stakeholder benefit.", "Partially tailors the message but remains generic or mismatched in detail.", "Explains specific, relevant benefits with an appropriate level of technical detail.", "Builds compelling, evidence-backed messages anticipating diverse questions and values."]},
    "Embraces and learns from failure": {"definition": "Analyzes setbacks, extracts lessons, and applies them to improve subsequent work.", "anchors": ["Avoids, blames, or discards failure without reflection.", "Acknowledges failure but identifies only surface causes or limited lessons.", "Accepts responsibility, analyzes root causes, and documents actionable learning.", "Applies learning iteratively and helps others respond constructively to failure."]},
    "Finds opportunities to create value": {"definition": "Recognizes unmet needs, inefficiencies, trends, and gaps that could benefit stakeholders.", "anchors": ["Waits for instructions and overlooks needs or improvement opportunities.", "Suggests vague or weakly supported improvements, usually when prompted.", "Identifies a meaningful opportunity and connects it to stakeholder benefit with evidence.", "Proactively identifies significant, feasible opportunities and supports likely impact with evidence."]},
    "Gathers data to support and refute ideas": {"definition": "Seeks credible evidence that can both validate and challenge assumptions or preferred solutions.", "anchors": ["Relies on opinion or ignores evidence that could challenge the preferred idea.", "Collects limited evidence and favors confirming information.", "Gathers credible supporting and opposing evidence and incorporates contradictions.", "Designs tests that could invalidate the preferred approach and pivots when contrary evidence is compelling."]},
    "Identifies impact for various stakeholders": {"definition": "Maps stakeholders and evaluates direct, indirect, positive, negative, short-term, and long-term effects.", "anchors": ["Focuses only on technical success or the immediate customer.", "Names some stakeholders but misses groups or analyzes impacts superficially.", "Considers key stakeholders and direct/indirect impacts, integrating feedback into decisions.", "Includes less obvious or marginalized groups and anticipates systemic, long-term, unintended consequences."]},
    "Integrates information from many sources": {"definition": "Connects diverse data, perspectives, and disciplines into a coherent understanding that informs decisions.", "anchors": ["Uses only familiar sources and ignores conflicts or missing perspectives.", "Uses multiple sources but makes superficial connections or leaves conflicts unresolved.", "Synthesizes credible, diverse sources and resolves minor discrepancies to inform a decision.", "Reconciles significant conflicts and uncovers a pattern or solution no source reveals alone."]},
}

SCORING_SCALE: Final[dict[str, str]] = {
    "NE": "Not elicited or insufficient evidence; excluded from scoring.",
    "0": "Not yet evident despite a clear opportunity.",
    "1": "Developing: partial, reactive, superficial, incomplete, or weakly supported.",
    "2": "Advancing: intentional, supported, and consequential for a decision or revision.",
    "3": "Proficient: proactive and adaptive in a complex/new context, with limitations or counterevidence addressed and transfer explained.",
}
